version: "3.9"
services:
  postgres:
    image: postgres:13.2
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 256M
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: inscricoes
    container_name: postgres

  backend:
    build:
      context: ./badminton-api
      target: dev
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    ports:
      - 5050:5050
    working_dir: /src
    volumes:
      - ./badminton-api:/src
      - bcdata:/node_modules
    container_name: backend
    entrypoint: yarn start

    
#  frontend:
#    build:
#      context: ./badminton
#      target: dev
#    ports:
#      - 3000:3000
#    working_dir: /src
#    volumes:
#      - ./badminton:/src
#      - fbdata:/node_modules
#    container_name: frontend
#    entrypoint: yarn start
#    stdin_open: true

volumes:
  pgdata:
#  fbdata:
  bcdata:
